genenv:
  enable: False

data:
  tokenizer: null
  train_files: []
  val_files: []
  prompt_key: question
  max_prompt_length: 28672
  max_response_length: 4096
  train_batch_size: 8
  val_batch_size: 8
  return_raw_input_ids: False
  return_raw_chat: True
  shuffle: True
  seed: 42
  sampler: null
  dataloader_num_workers: 8

custom_reward_function:
  question: null
  reward: null

ray_kwargs:
  ray_init:
    runtime_env:
      env_vars:
        HF_HOME: /data/yanfeizhang/AgenticOPSD/.cache/huggingface
        HF_DATASETS_CACHE: /data/yanfeizhang/AgenticOPSD/.cache/huggingface/datasets
        TMPDIR: /data/yanfeizhang/AgenticOPSD/.tmp

transfer_queue:
  enable: False

global_profiler:
  enable: False
  global_tool_config:
    nsys: {}
  tool: "nsys"
  steps: null

sandbox_fusion:
  enable: False
  enable_resource_pool: null
  n_gpus_per_node: null
  nnodes: null

reward_model:
  enable: False
  num_workers: null
  reward_loop_source: null
  enable_resource_pool: False
  reward_manager: na
  n_gpus_per_node: 0
  nnodes: 1
  rollout: {}
  model:
    path: null
reward_manager:
  name: BrowsecompRewardManager
  module:
      path: optimize.run
      name: BrowsecompRewardManager
  reward_loop_source: custom
  reward_loop_module_path: optimize.run
  reward_loop_class_name: BrowsecompRewardManager
  rollout: {}
  model:
    path: null
    input_tokenizer: null
  reward_kwargs: null

reward:
  num_workers: 0
  reward_manager:
    name: browsecomp_reward
    source: custom
    module:
      path: optimize.run
      name: BrowsecompRewardManager
  reward_model:
    enable: False
    enable_resource_pool: False
    reward_manager: na
    n_gpus_per_node: 0
    nnodes: 1
    rollout: {}
  reward_kwargs: {}
  sandbox_fusion:
    enable: False
    enable_resource_pool: null
    n_gpus_per_node: null
    nnodes: null

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: /data/huggingface_models/Qwen3-8B
    external_lib: null
    override_config:
      attn_implementation: sdpa
    enable_gradient_checkpointing: True
    use_remove_padding: True

  actor:
    strategy: fsdp
    rollout_n: ${actor_rollout_ref.rollout.n}
    _target_: verl.workers.config.actor.FSDPActorConfig
    loss_agg_mode: token-mean
    ppo_mini_batch_size: 14
    ppo_micro_batch_size: null
    ppo_micro_batch_size_per_gpu: 4
    use_dynamic_bsz: True
    ppo_max_token_len_per_gpu: 28672
    grad_clip: 1.0
    clip_ratio: 0.2
    clip_ratio_low: -1
    clip_ratio_high: -1
    entropy_coeff: 0.001
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    ppo_epochs: 1
    shuffle: False
    ulysses_sequence_parallel_size: 1
    entropy_from_logits_with_chunking: False
    entropy_checkpointing: False
    use_remove_padding: True
    optim:
      lr: 1e-6
      lr_warmup_steps_ratio: 0.
      total_training_steps: -1
      weight_decay: 0.01
      lr_warmup_steps: -1
      betas: [0.9, 0.999]
      clip_grad: 1.0
      optimizer: AdamW
      optimizer_impl: torch.optim
      min_lr_ratio: null
      warmup_style: null
      lr_scheduler_type: constant
      num_cycles: 0.5
      zero_indexed_step: true
      override_optimizer_config: null
    checkpoint:
      save_contents: [model, optimizer, extra]
      load_contents: [model, optimizer, extra]
      async_save: false
      mbridge_config: {}
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      wrap_policy:
        min_num_params: 0
      param_offload: False
      grad_offload: False
      optimizer_offload: True
      fsdp_size: -1
      entropy_from_logits_with_chunking: False
      entropy_checkpointing: False
      use_torch_compile: True
      forward_only: False

  ref:
    strategy: fsdp
    rollout_n: ${actor_rollout_ref.rollout.n}
    _target_: verl.workers.config.actor.FSDPActorConfig
    use_torch_compile: True
    entropy_from_logits_with_chunking: False
    entropy_checkpointing: False
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      param_offload: False
      wrap_policy:
        min_num_params: 0
      entropy_from_logits_with_chunking: False
      entropy_checkpointing: False
      use_torch_compile: True
      forward_only: True
    log_prob_micro_batch_size: null
    log_prob_micro_batch_size_per_gpu: 8
    log_prob_use_dynamic_bsz: True
    log_prob_max_token_len_per_gpu: 28672
    ulysses_sequence_parallel_size: 1

  rollout:
    _target_: verl.workers.config.rollout.RolloutConfig
    name: vllm
    nnodes: ${trainer.nnodes}
    n_gpus_per_node: ${trainer.n_gpus_per_node}
    temperature: 1.0
    top_k: -1
    top_p: 1.0
    prompt_length: 28672
    response_length: 4096
    max_model_len: 32768
    dtype: bfloat16
    gpu_memory_utilization: 0.35
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy
    data_parallel_size: 1
    expert_parallel_size: 1
    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    max_num_batched_tokens: 4096
    max_num_seqs: 32
    log_prob_micro_batch_size: null
    log_prob_micro_batch_size_per_gpu: 8
    log_prob_use_dynamic_bsz: True
    log_prob_max_token_len_per_gpu: 28672
    enable_chunked_prefill: True
    do_sample: True
    n: 2
    mode: async
    val_kwargs:
      do_sample: False
    agent:
      default_agent_loop: browsecomp_zh_agent
      agent_loop_manager_class: optimize.run.BrowsecompZHAgentLoopManager

critic:
  _target_: verl.workers.config.critic.FSDPCriticConfig
  enable: False
  strategy: fsdp
  rollout_n: ${actor_rollout_ref.rollout.n}
  optim:
    lr: 1e-5
    lr_warmup_steps_ratio: 0.05
    total_training_steps: -1
    weight_decay: 0.01
    lr_warmup_steps: -1
    betas: [0.9, 0.999]
    clip_grad: 1.0
    optimizer: AdamW
    optimizer_impl: torch.optim
    min_lr_ratio: null
    warmup_style: null
    lr_scheduler_type: constant
    num_cycles: 0.5
    zero_indexed_step: true
    override_optimizer_config: null
  model:
    path: null
    tokenizer_path: null
    override_config: {}
    external_lib: null
    enable_gradient_checkpointing: True
    use_remove_padding: True
  loss_agg_mode: token-mean
  ppo_mini_batch_size: 8
  ppo_micro_batch_size_per_gpu: 4
  use_dynamic_bsz: True
  ppo_max_token_len_per_gpu: 28672
  grad_clip: 1.0
  cliprange_value: 0.5
  ppo_epochs: 1
  shuffle: False
  ulysses_sequence_parallel_size: 1

algorithm:
  adv_estimator: grpo
  gamma: 1.0
  lam: 1.0
  use_kl_in_reward: False
  norm_adv_by_std_in_grpo: True

trainer:
  device: cuda
  total_training_steps: 1000
  total_epochs: 10
  project_name: agentic_ospd
  experiment_name: browsecomp_zh
  logger: [console]
  nnodes: 1
  n_gpus_per_node: 7
  reward_manager: na
  save_freq: 100
  val_before_train: False
  test_freq: 10
  critic_warmup: 0
  default_local_dir: /data/yanfeizhang/AgenticOPSD/workspace/Browsecomp_zh/outputs/checkpoints
